micronaut:
  application:
    name: wallet
  server:
    port: ${SERVICE_PORT:8082}
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"